### ISSUE TITLE
Modifying configurtion on Mikrotik doesn't work

### ISSUE THREAD

**Issue by etiennesw** [pear2/pear2.php.net#37]
Hi,

First of all, I'd like to thank you for your project. Seems you have put a lot of work into it.

I am not sure if this is the best place to post but other channels seem down.

I am testing this API with a Mikrotik RouterOS v3.20 from a Raspberry PI with PHP5 installed.

When retrieving data from the Mikrotik, it works fine, such as the basic example of the arp table.

$util->setMenu('/ip arp');

foreach ($util->getAll() as $item) {
    echo 'IP: ', $item->getProperty('address'),
         '---> MAC: ', $item->getProperty('mac-address')."<br>";

However, when I try to enable/disable or remove an arp entry, nothing happens, not even an error.

$util->setMenu('/ip arp')->remove(8);

 or this

$util->setMenu('/ip arp');
$util->disable(RouterOS\Query::where('comment', 'DISABLE ME'));

The api connection is successful, as I see it in the Mikrotik logs, however, nothing happens.

Could the problem be related to the old RouterOS version?

If I perform the command to disable id 8 from the Mikrotik terminal it works, so its the API that somehow fails.

Do you have any idea and suggestions?

Thanks

Rgs
ETienne

**Comment by saltybeagle** [comment]
Not an issue with the pear2.php.net website.

**Comment by etiennesw** [comment]
Sorry, I posted in the wrong tab.

My fault.

Rgs
Etienne
